### ISSUE TITLE
Error 99 address not available

### ISSUE THREAD

**Issue by lettore** [hassio-addons/addon-matrix#10]
# Problem/Motivation

The addon could not start because of Error 99

## Expected behavior

Addon start correctly

## Actual behavior

Addon start but works just the home page, not the service, here the log
2019-03-24 08:24:10,302 - twisted - 240 - ERROR -  - Traceback (most recent call last):
2019-03-24 08:24:10,302 - twisted - 240 - ERROR -  -   File "/usr/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1361, in startListening
2019-03-24 08:24:10,303 - twisted - 240 - ERROR -  -     skt.bind(addr)
2019-03-24 08:24:10,303 - twisted - 240 - ERROR -  - OSError: [Errno 99] Address not available
2019-03-24 08:24:10,304 - twisted - 240 - ERROR -  - 
2019-03-24 08:24:10,304 - twisted - 240 - ERROR -  - During handling of the above exception, another exception occurred:
2019-03-24 08:24:10,304 - twisted - 240 - ERROR -  - 
2019-03-24 08:24:10,305 - twisted - 240 - ERROR -  - Traceback (most recent call last):
2019-03-24 08:24:10,305 - twisted - 240 - ERROR -  -   File "/usr/lib/python3.6/site-packages/synapse/app/_base.py", line 273, in start
2019-03-24 08:24:10,305 - twisted - 240 - ERROR -  -     hs.start_listening(listeners)
2019-03-24 08:24:10,306 - twisted - 240 - ERROR -  -   File "/usr/lib/python3.6/site-packages/synapse/app/homeserver.py", line 259, in start_listening
2019-03-24 08:24:10,306 - twisted - 240 - ERROR -  -     self._listener_http(config, listener)
2019-03-24 08:24:10,306 - twisted - 240 - ERROR -  -   File "/usr/lib/python3.6/site-packages/synapse/app/homeserver.py", line 138, in _listener_http
2019-03-24 08:24:10,307 - twisted - 240 - ERROR -  -     reactor=self.get_reactor(),
2019-03-24 08:24:10,307 - twisted - 240 - ERROR -  -   File "/usr/lib/python3.6/site-packages/synapse/app/_base.py", line 208, in listen_ssl
2019-03-24 08:24:10,307 - twisted - 240 - ERROR -  -     check_bind_error(e, address, bind_addresses)
2019-03-24 08:24:10,308 - twisted - 240 - ERROR -  -   File "/usr/lib/python3.6/site-packages/synapse/app/__init__.py", line 49, in check_bind_error
2019-03-24 08:24:10,308 - twisted - 240 - ERROR -  -     raise e
2019-03-24 08:24:10,308 - twisted - 240 - ERROR -  -   File "/usr/lib/python3.6/site-packages/synapse/app/_base.py", line 204, in listen_ssl
2019-03-24 08:24:10,309 - twisted - 240 - ERROR -  -     address
2019-03-24 08:24:10,309 - twisted - 240 - ERROR -  -   File "/usr/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 522, in listenSSL
2019-03-24 08:24:10,309 - twisted - 240 - ERROR -  -     port = self.listenTCP(port, tlsFactory, backlog, interface)
2019-03-24 08:24:10,310 - twisted - 240 - ERROR -  -   File "/usr/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 495, in listenTCP
2019-03-24 08:24:10,310 - twisted - 240 - ERROR -  -     p.startListening()
2019-03-24 08:24:10,310 - twisted - 240 - ERROR -  -   File "/usr/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1363, in startListening
2019-03-24 08:24:10,311 - twisted - 240 - ERROR -  -     raise CannotListenError(self.interface, self.port, le)
2019-03-24 08:24:10,311 - twisted - 240 - ERROR -  - twisted.internet.error.CannotListenError: Couldn't listen on ::1:8008: [Errno 99] Address not available.
2019-03-24 08:24:10,312 - synapse.handlers.deactivate_account - 144 - INFO - user_parter_loop-0 - User parter finished: stopping
2019-03-24 08:24:10,314 - synapse.handlers.presence - 240 - INFO -  - Performing _on_shutdown. Persisting 0 unpersisted changes
2019-03-24 08:24:10,315 - synapse.handlers.presence - 248 - INFO -  - Finished _on_shutdown
2019-03-24 08:24:10,316 - synapse.metrics - 372 - INFO -  - Collecting gc 0
2019-03-24 08:24:10,338 - twisted - 240 - CRITICAL -  - Unhandled error in Deferred:
2019-03-24 08:24:10,339 - twisted - 240 - CRITICAL -  - 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1361, in startListening
    skt.bind(addr)
OSError: [Errno 99] Address not available

## Steps to reproduce

Start a fresh instance of the addon deleting the matrix.yaml file

## Proposed changes

For make it work I had to remove ::1 address from the binds part of matrix.yaml file

**Comment by sqldiablo** [comment]
Your proposed change lets the add-on start for me, but it never starts listening on port 8448. I can get to the page at port 8558, but it won't let me register to my home server.

**Comment by tooljose88** [comment]
I have a rPi 2, and Matrix is not working. I have opened 3 ports (8558, 8448, 8008) and the server_name is set to "_homename_.duckdns.org"

This is the log:

```
2019-04-13 01:25:06,737 - synapse.handlers.deactivate_account - 134 - INFO - user_parter_loop-0 - Starting user parter
2019-04-13 01:25:06,764 - synapse.federation.federation_server - 822 - INFO -  - Registering federation EDU handler for 'm.receipt'
2019-04-13 01:25:06,769 - synapse.federation.federation_server - 842 - INFO -  - Registering federation query handler for 'client_keys'
2019-04-13 01:25:06,779 - synapse.federation.federation_server - 822 - INFO -  - Registering federation EDU handler for 'm.direct_to_device'
2019-04-13 01:25:06,951 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x74585690> to path b'/_matrix/client/api/v1'
2019-04-13 01:25:06,954 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x74585690> to path b'/_matrix/client/r0'
2019-04-13 01:25:06,957 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x74585690> to path b'/_matrix/client/unstable'
2019-04-13 01:25:06,959 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x74585690> to path b'/_matrix/client/v2_alpha'
2019-04-13 01:25:06,962 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x74585690> to path b'/_matrix/client/versions'
2019-04-13 01:25:06,964 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.well_known.WellKnownResource object at 0x74563530> to path b'/.well-known/matrix/client'
2019-04-13 01:25:06,966 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching FilePath('/usr/lib/python3.6/site-packages/synapse/static') to path b'/_matrix/static'
2019-04-13 01:25:06,968 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.media.v1.media_repository.MediaRepositoryResource object at 0x74553190> to path b'/_matrix/media/r0'
2019-04-13 01:25:06,971 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.media.v1.media_repository.MediaRepositoryResource object at 0x74553190> to path b'/_matrix/media/v1'
2019-04-13 01:25:06,973 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.media.v0.content_repository.ContentRepoResource object at 0x74563650> to path b'/_matrix/content'
2019-04-13 01:25:06,975 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.federation.transport.server.TransportLayerServer object at 0x74563c90> to path b'/_matrix/federation'
2019-04-13 01:25:06,978 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.key.v2.KeyApiV2Resource object at 0x7457a1b0> to path b'/_matrix/key/v2'
2019-04-13 01:25:06,991 - twisted - 242 - INFO -  - SynapseSite (TLS) starting on 8008
2019-04-13 01:25:07,013 - twisted - 242 - ERROR -  - Traceback (most recent call last):
2019-04-13 01:25:07,016 - twisted - 242 - ERROR -  -   File "/usr/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1361, in startListening
2019-04-13 01:25:07,018 - twisted - 242 - ERROR -  -     skt.bind(addr)
2019-04-13 01:25:07,022 - twisted - 242 - ERROR -  - OSError: [Errno 99] Address not available
2019-04-13 01:25:07,025 - twisted - 242 - ERROR -  - 
2019-04-13 01:25:07,027 - twisted - 242 - ERROR -  - During handling of the above exception, another exception occurred:
2019-04-13 01:25:07,030 - twisted - 242 - ERROR -  - 
2019-04-13 01:25:07,033 - twisted - 242 - ERROR -  - Traceback (most recent call last):
2019-04-13 01:25:07,036 - twisted - 242 - ERROR -  -   File "/usr/lib/python3.6/site-packages/synapse/app/_base.py", line 279, in start
2019-04-13 01:25:07,039 - twisted - 242 - ERROR -  -     hs.start_listening(listeners)
2019-04-13 01:25:07,042 - twisted - 242 - ERROR -  -   File "/usr/lib/python3.6/site-packages/synapse/app/homeserver.py", line 259, in start_listening
2019-04-13 01:25:07,045 - twisted - 242 - ERROR -  -     self._listener_http(config, listener)
2019-04-13 01:25:07,047 - twisted - 242 - ERROR -  -   File "/usr/lib/python3.6/site-packages/synapse/app/homeserver.py", line 138, in _listener_http
2019-04-13 01:25:07,050 - twisted - 242 - ERROR -  -     reactor=self.get_reactor(),
2019-04-13 01:25:07,053 - twisted - 242 - ERROR -  -   File "/usr/lib/python3.6/site-packages/synapse/app/_base.py", line 214, in listen_ssl
2019-04-13 01:25:07,056 - twisted - 242 - ERROR -  -     check_bind_error(e, address, bind_addresses)
2019-04-13 01:25:07,059 - twisted - 242 - ERROR -  -   File "/usr/lib/python3.6/site-packages/synapse/app/__init__.py", line 49, in check_bind_error
2019-04-13 01:25:07,061 - twisted - 242 - ERROR -  -     raise e
2019-04-13 01:25:07,064 - twisted - 242 - ERROR -  -   File "/usr/lib/python3.6/site-packages/synapse/app/_base.py", line 210, in listen_ssl
2019-04-13 01:25:07,067 - twisted - 242 - ERROR -  -     address
2019-04-13 01:25:07,070 - twisted - 242 - ERROR -  -   File "/usr/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 522, in listenSSL
2019-04-13 01:25:07,073 - twisted - 242 - ERROR -  -     port = self.listenTCP(port, tlsFactory, backlog, interface)
2019-04-13 01:25:07,076 - twisted - 242 - ERROR -  -   File "/usr/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 495, in listenTCP
2019-04-13 01:25:07,079 - twisted - 242 - ERROR -  -     p.startListening()
2019-04-13 01:25:07,081 - twisted - 242 - ERROR -  -   File "/usr/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1363, in startListening
2019-04-13 01:25:07,084 - twisted - 242 - ERROR -  -     raise CannotListenError(self.interface, self.port, le)
2019-04-13 01:25:07,087 - twisted - 242 - ERROR -  - twisted.internet.error.CannotListenError: Couldn't listen on 83.43.73.170:8008: [Errno 99] Address not available.
2019-04-13 01:25:07,097 - synapse.handlers.deactivate_account - 144 - INFO - user_parter_loop-0 - User parter finished: stopping
2019-04-13 01:25:07,107 - synapse.handlers.presence - 240 - INFO -  - Performing _on_shutdown. Persisting 0 unpersisted changes
2019-04-13 01:25:07,110 - synapse.handlers.presence - 248 - INFO -  - Finished _on_shutdown
2019-04-13 01:25:07,117 - synapse.metrics - 372 - INFO -  - Collecting gc 0
2019-04-13 01:25:07,269 - twisted - 242 - CRITICAL -  - Unhandled error in Deferred:
2019-04-13 01:25:07,272 - twisted - 242 - CRITICAL -  - 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1361, in startListening
    skt.bind(addr)
OSError: [Errno 99] Address not available
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/synapse/app/_base.py", line 279, in start
    hs.start_listening(listeners)
  File "/usr/lib/python3.6/site-packages/synapse/app/homeserver.py", line 259, in start_listening
    self._listener_http(config, listener)
  File "/usr/lib/python3.6/site-packages/synapse/app/homeserver.py", line 138, in _listener_http
    reactor=self.get_reactor(),
  File "/usr/lib/python3.6/site-packages/synapse/app/_base.py", line 214, in listen_ssl
    check_bind_error(e, address, bind_addresses)
  File "/usr/lib/python3.6/site-packages/synapse/app/__init__.py", line 49, in check_bind_error
    raise e
  File "/usr/lib/python3.6/site-packages/synapse/app/_base.py", line 210, in listen_ssl
    address
  File "/usr/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 522, in listenSSL
    port = self.listenTCP(port, tlsFactory, backlog, interface)
  File "/usr/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 495, in listenTCP
    p.startListening()
  File "/usr/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1363, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on 83.43.73.170:8008: [Errno 99] Address not available.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python3.6/site-packages/synapse/app/homeserver.py", line 439, in start
    _base.start(hs, config.listeners)
  File "/usr/lib/python3.6/site-packages/synapse/app/_base.py", line 288, in start
    sys.exit(1)
SystemExit: 1
2019-04-13 01:25:07,312 - twisted - 242 - INFO -  - (TLS Port 8008 Closed)
2019-04-13 01:25:07,320 - twisted - 242 - INFO -  - Main loop terminated.
2019-04-13 01:25:25,223 - root - 211 - WARNING - None - ***** STARTING SERVER *****
2019-04-13 01:25:25,244 - synapse.util.versionstring - 82 - INFO - None - Failed to check for git repository: [Errno 2] No such file or directory: 'git': 'git'
2019-04-13 01:25:25,251 - root - 214 - WARNING - None - Server /usr/lib/python3.6/site-packages/synapse/app/homeserver.py version 0.99.3
2019-04-13 01:25:25,253 - root - 216 - INFO - None - Server hostname:homename.duckdns.org
2019-04-13 01:25:25,259 - twisted - 242 - INFO - None - Redirected stdout/stderr to logs
2019-04-13 01:25:25,298 - synapse.util.versionstring - 82 - INFO - None - Failed to check for git repository: [Errno 2] No such file or directory: 'git': 'git'
2019-04-13 01:25:25,307 - synapse.app.homeserver - 358 - INFO - None - Preparing database: sqlite3...
2019-04-13 01:25:25,348 - synapse.storage.prepare_database - 223 - INFO - None - Upgrading schema to v53
2019-04-13 01:25:25,360 - synapse.app.homeserver - 376 - INFO - None - Database prepared in sqlite3.
2019-04-13 01:25:25,362 - synapse.server - 222 - INFO - None - Setting up.
```
